from datetime import date

N_LEGITIMATE_CUSTOMERS = 8000
N_FRAUD_RING_CUSTOMERS = 800
TOTAL_CUSTOMERS = N_LEGITIMATE_CUSTOMERS + N_FRAUD_RING_CUSTOMERS

MIN_RING_SIZE = 2
MAX_RING_SIZE = 10
RING_SIZE_DISTRIBUTION = {
    2: 0.30,
    3: 0.25,
    4: 0.18,
    5: 0.10,
    6: 0.06,
    7: 0.04,
    8: 0.03,
    9: 0.025,
    10: 0.015,
}

SIMULATION_START_DATE = date(2025, 1, 1)
SIMULATION_END_DATE = date(2026, 6, 30)
SIMULATION_DAYS = (SIMULATION_END_DATE - SIMULATION_START_DATE).days

RANDOM_SEED = 42

MIN_AGE = 18
MAX_AGE = 75
AGE_MEAN = 40
AGE_STD_DEV = 12

MIN_ANNUAL_INCOME = 15_000
MAX_ANNUAL_INCOME = 250_000
INCOME_LOG_MEAN = 10.9
INCOME_LOG_SIGMA = 0.55

MIN_CREDIT_SCORE = 300
MAX_CREDIT_SCORE = 850
CREDIT_SCORE_MEAN = 680
CREDIT_SCORE_STD_DEV = 70

LEGITIMATE_LABEL = 0
FRAUD_LABEL = 1
NO_RING_ID = ""

ATTRIBUTE_TYPES = ("phone", "email", "address", "device")
MIN_SHARED_ATTRIBUTES_PER_RING = 1
MAX_SHARED_ATTRIBUTES_PER_RING = 3

PHONE_PREFIX = "555"
PHONE_MIDDLE_SLICE_START = -7
PHONE_MIDDLE_SLICE_END = -4
PHONE_LAST_SLICE_START = -4
SSN_PREFIX = "SYN"
DEVICE_BYTE_LENGTH = 16
ID_HEX_LENGTH = 12
UUID_BYTE_LENGTH = 16
UUID_GROUP_LENGTHS = (8, 4, 4, 4, 12)
ZIP_MIN = 10_000
ZIP_MAX = 99_999
SYNTHETIC_SSN_PART_1_MIN = 100
SYNTHETIC_SSN_PART_1_MAX = 999
SYNTHETIC_SSN_PART_2_MIN = 10
SYNTHETIC_SSN_PART_2_MAX = 99
SYNTHETIC_SSN_PART_3_MIN = 1000
SYNTHETIC_SSN_PART_3_MAX = 9999

BASE_CREDIT_LIMIT_MIN = 500
BASE_CREDIT_LIMIT_MAX = 8_000
LIMIT_INCREASE_MIN = 500
LIMIT_INCREASE_MAX = 3_000
LIMIT_ROUNDING = 100

LEGIT_UTILIZATION_MIN = 0.10
LEGIT_UTILIZATION_MAX = 0.50
LEGIT_PAYMENT_DROP_MIN = 0.08
LEGIT_PAYMENT_DROP_MAX = 0.25
LEGIT_LIMIT_INCREASE_CHANCE = 0.18
LEGIT_UTILIZATION_NOISE_STD = 0.08

FRAUD_NORMAL_UTILIZATION_MIN = 0.12
FRAUD_NORMAL_UTILIZATION_MAX = 0.48
FRAUD_NORMAL_UTILIZATION_NOISE_STD = 0.07
FRAUD_BUSTOUT_UTILIZATION_MIN = 0.90
FRAUD_BUSTOUT_UTILIZATION_MAX = 1.00
FRAUD_BUSTOUT_LIFETIME_MIN = 0.70
FRAUD_BUSTOUT_LIFETIME_MAX = 0.90
FRAUD_BUSTOUT_PURCHASES_MIN = 2
FRAUD_BUSTOUT_PURCHASES_MAX = 4
FRAUD_BUSTOUT_EVENT_DAY_STEP_MIN = 1
FRAUD_BUSTOUT_EVENT_DAY_STEP_MAX = 4
ACCOUNT_ABANDONMENT_DELAY_DAYS_MIN = 7
ACCOUNT_ABANDONMENT_DELAY_DAYS_MAX = 21

MONTH_DAYS = 30
DAYS_PER_YEAR = 365
DOB_JITTER_DAYS = 365
FIRST_EVENT_INDEX = 0
EVENT_DAY_MIN = 1
EVENT_DAY_WEEK_MAX = 7
PAYMENT_DAY_MIN = 12
PAYMENT_DAY_MAX = 23

RING_ID_PREFIX = "ring"
RING_NUMBER_START = 1
RING_ID_WIDTH = 4
UTILIZATION_DECIMALS = 3

OUTPUT_FILES = {
    "customers": "customers.csv",
    "phones": "phones.csv",
    "emails": "emails.csv",
    "addresses": "addresses.csv",
    "devices": "devices.csv",
    "links": "customer_attribute_links.csv",
    "events": "events.csv",
    "ring_ground_truth": "ring_ground_truth.csv",
}

INCOME_HISTOGRAM_BINS = 20
CREDIT_SCORE_HISTOGRAM_BINS = 20
MAX_HISTOGRAM_TOTAL_VARIATION = 0.20
MAX_MEAN_RELATIVE_DIFFERENCE = 0.08
