import argparse
from pathlib import Path
import pandas as pd


def load_edges(csv_path: Path) -> pd.DataFrame:
    """Load the edge list CSV.

    Expected columns:
        source_customer_id
        target_customer_id
        shared_phone
        shared_email
        shared_address
        shared_device
        shared_attribute_count
    """
    return pd.read_csv(csv_path)


CORE_FLAG_COLUMNS = ["shared_phone", "shared_email", "shared_address", "shared_device"]


def edge_flag_columns(edges: pd.DataFrame) -> list[str]:
    """Core shared-attribute flags plus any extra ``shared_<type>`` flags."""
    extra = [
        column
        for column in edges.columns
        if column.startswith("shared_")
        and column != "shared_attribute_count"
        and column not in CORE_FLAG_COLUMNS
    ]
    return CORE_FLAG_COLUMNS + extra


def compute_features(edges: pd.DataFrame) -> pd.DataFrame:
    """Compute red‑flag network features per customer.

    Returns a DataFrame with columns:
        customer_id
        phone_shared_count
        email_shared_count
        address_shared_count
        device_shared_count
        <extra type>_shared_count (one per extra ``shared_<type>`` edge flag)
        network_degree
        shared_attribute_count

    Each ``*_shared_count`` is the number of other customers this customer
    shares that attribute type with. Only customers that appear in at least
    one edge are returned, sorted by ``customer_id``.
    """
    flag_columns = edge_flag_columns(edges)
    for column in flag_columns:
        if column not in edges.columns:
            edges = edges.assign(**{column: 0})
    count_columns = [f"{column.removeprefix('shared_')}_shared_count" for column in flag_columns]
    output_columns = ["customer_id", *count_columns, "network_degree", "shared_attribute_count"]
    if edges.empty:
        return pd.DataFrame(columns=output_columns)

    value_columns = [*flag_columns, "shared_attribute_count"]
    # Each undirected edge contributes to both of its endpoints.
    endpoint_rows = pd.concat(
        [
            edges[["source_customer_id", *value_columns]].rename(columns={"source_customer_id": "customer_id"}),
            edges[["target_customer_id", *value_columns]].rename(columns={"target_customer_id": "customer_id"}),
        ],
        ignore_index=True,
    )
    endpoint_rows[flag_columns] = endpoint_rows[flag_columns].astype(bool).astype("int64")
    grouped = endpoint_rows.groupby("customer_id", sort=True)
    features = grouped[value_columns].sum()
    features["network_degree"] = grouped.size()
    features = features.rename(columns=dict(zip(flag_columns, count_columns))).reset_index()
    features[output_columns[1:]] = features[output_columns[1:]].astype("int64")
    return features[output_columns]


def save_features(df: pd.DataFrame, out_path: Path) -> None:
    """Save the features DataFrame to CSV, creating parent directories as needed."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)
    print(f"Saved red-flag features to {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate red‑flag network features for each customer.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).parents[2] / "data" / "processed" / "customer_edges.csv",
        help="Path to the edge CSV generated by build_customer_graph.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parents[2] / "data" / "processed" / "customer_features.csv",
        help="Path where the per‑customer feature CSV will be written.",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        raise FileNotFoundError(f"Input edge file not found: {args.input}")

    edges_df = load_edges(args.input)
    features_df = compute_features(edges_df)
    save_features(features_df, args.output)


if __name__ == "__main__":
    main()
