import argparse
from collections import defaultdict
from pathlib import Path
import pandas as pd


def load_edges(csv_path: Path) -> pd.DataFrame:
    """Load the edge list CSV.

    Expected columns:
        source_customer_id
        target_customer_id
        shared_phone
        shared_email
        shared_address
        shared_device
        shared_attribute_count
    """
    return pd.read_csv(csv_path)


def compute_features(edges: pd.DataFrame) -> pd.DataFrame:
    """Compute red‑flag network features per customer.

    Returns a DataFrame with columns:
        customer_id
        phone_shared_count
        email_shared_count
        address_shared_count
        device_shared_count
        network_degree
        shared_attribute_count
    """
    # Initialize counters
    phone_cnt = defaultdict(int)
    email_cnt = defaultdict(int)
    address_cnt = defaultdict(int)
    device_cnt = defaultdict(int)
    degree_cnt = defaultdict(int)
    attr_cnt = defaultdict(int)  # sum of shared_attribute_count per incident edge

    for _, row in edges.iterrows():
        src = row["source_customer_id"]
        tgt = row["target_customer_id"]
        # degree increases by one for each incident edge
        degree_cnt[src] += 1
        degree_cnt[tgt] += 1
        # shared attribute counts (binary flags)
        if row["shared_phone"]:
            phone_cnt[src] += 1
            phone_cnt[tgt] += 1
        if row["shared_email"]:
            email_cnt[src] += 1
            email_cnt[tgt] += 1
        if row["shared_address"]:
            address_cnt[src] += 1
            address_cnt[tgt] += 1
        if row["shared_device"]:
            device_cnt[src] += 1
            device_cnt[tgt] += 1
        # sum of shared attribute count per edge
        shared_attr = row["shared_attribute_count"]
        if shared_attr:
            attr_cnt[src] += shared_attr
            attr_cnt[tgt] += shared_attr

    # Gather all unique customers observed in the edge list
    all_customers = set(degree_cnt.keys())
    # Build rows
    rows = []
    for cust in sorted(all_customers):
        rows.append({
            "customer_id": cust,
            "phone_shared_count": phone_cnt.get(cust, 0),
            "email_shared_count": email_cnt.get(cust, 0),
            "address_shared_count": address_cnt.get(cust, 0),
            "device_shared_count": device_cnt.get(cust, 0),
            "network_degree": degree_cnt.get(cust, 0),
            "shared_attribute_count": attr_cnt.get(cust, 0),
        })
    return pd.DataFrame(rows)


def save_features(df: pd.DataFrame, out_path: Path) -> None:
    """Save the features DataFrame to CSV, creating parent directories as needed."""
    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_path, index=False)
    print(f"Saved red-flag features to {out_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate red‑flag network features for each customer.")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path(__file__).parents[2] / "data" / "processed" / "customer_edges.csv",
        help="Path to the edge CSV generated by build_customer_graph.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).parents[2] / "data" / "processed" / "customer_features.csv",
        help="Path where the per‑customer feature CSV will be written.",
    )
    args = parser.parse_args()

    if not args.input.is_file():
        raise FileNotFoundError(f"Input edge file not found: {args.input}")

    edges_df = load_edges(args.input)
    features_df = compute_features(edges_df)
    save_features(features_df, args.output)


if __name__ == "__main__":
    main()
