import argparse
import itertools
from pathlib import Path
import pandas as pd


def load_ground_truth(csv_path: Path) -> dict:
    """Load ring ground truth and return mapping ring_id -> set of customer_ids."""
    df = pd.read_csv(csv_path)
    ring_map = {}
    for ring_id, group in df.groupby("ring_id"):
        ring_map[ring_id] = set(group["customer_id"].tolist())
    return ring_map


def load_edges(csv_path: Path) -> set:
    """Load edge list and return a set of unordered customer pairs.

    Edge CSV columns: source_customer_id, target_customer_id, ...
    """
    df = pd.read_csv(csv_path, usecols=["source_customer_id", "target_customer_id"])
    edge_set = set()
    for _, row in df.iterrows():
        a, b = row["source_customer_id"], row["target_customer_id"]
        # store unordered tuple
        edge_set.add(tuple(sorted((a, b))))
    return edge_set


def evaluate_ring_connectivity(ring_customers: set, edge_set: set) -> tuple[int, int]:
    """Return (total_pairs, connected_pairs) for a given ring.

    total_pairs = n * (n-1) / 2 for n customers in the ring.
    connected_pairs = number of those pairs present in ``edge_set``.
    """
    n = len(ring_customers)
    if n < 2:
        return 0, 0
    total_pairs = n * (n - 1) // 2
    connected = 0
    for a, b in itertools.combinations(sorted(ring_customers), 2):
        if (a, b) in edge_set:
            connected += 1
    return total_pairs, connected


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate that fraud rings are well‑connected in the customer graph.")
    parser.add_argument(
        "--ground-truth",
        type=Path,
        default=Path(__file__).parents[2] / "data" / "raw" / "ring_ground_truth.csv",
        help="Path to ring_ground_truth.csv.",
    )
    parser.add_argument(
        "--edges",
        type=Path,
        default=Path(__file__).parents[2] / "data" / "processed" / "customer_edges.csv",
        help="Path to the edge list generated by build_customer_graph.",
    )
    args = parser.parse_args()

    if not args.ground_truth.is_file():
        raise FileNotFoundError(f"Ground truth file not found: {args.ground_truth}")
    if not args.edges.is_file():
        raise FileNotFoundError(f"Edge list file not found: {args.edges}")

    ring_map = load_ground_truth(args.ground_truth)
    edge_set = load_edges(args.edges)

    total_pairs_all = 0
    connected_pairs_all = 0
    print("Ring connectivity summary (ring_id, total_pairs, connected_pairs, ratio)")
    for ring_id, customers in ring_map.items():
        total, connected = evaluate_ring_connectivity(customers, edge_set)
        total_pairs_all += total
        connected_pairs_all += connected
        ratio = (connected / total) if total > 0 else 0.0
        print(f"{ring_id:10s} {total:6d} {connected:6d} {ratio:.3f}")

    overall_ratio = (connected_pairs_all / total_pairs_all) if total_pairs_all > 0 else 0.0
    print("\nOverall connectivity across all rings:")
    print(f"Total pairs: {total_pairs_all}")
    print(f"Connected pairs: {connected_pairs_all}")
    print(f"Overall ratio: {overall_ratio:.3f}")


if __name__ == "__main__":
    main()

